### ISSUE TITLE
Anchor out of range parts

### ISSUE THREAD

**Issue by Pengalu** [TickoGrey/Object-Loader#1]
Hey there! I really like this script but I thought it might be a good idea to Anchor out of range parts since that can also heavily reduce lag. I'm not sure what your usecase it so it might not be a good idea for you yourself but for the public release it could help a lot.

Thank you for your time!

**Comment by TickoGrey** [comment]
That's actually a good idea! when I was making this script all my parts were already anchored so it wasn't in my mind but I think I will update with that!

**Comment by TickoGrey** [comment]
Done!
